import {
  AlertCircle,
  ArrowLeft,
  Building,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleCheck,
  CircleX,
  ClipboardList,
  Clock,
  Download,
  Eye,
  EyeOff,
  Filter,
  GripVertical,
  Home,
  Inbox,
  Info,
  LayoutTemplate,
  LifeBuoy,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  Pencil,
  Phone,
  Plus,
  Search,
  Settings,
  Sparkles,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  UserCog,
  UserPlus,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  alert: AlertCircle,
  arrowLeft: ArrowLeft,
  building: Building,
  calendar: Calendar,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  circleCheck: CircleCheck,
  circleX: CircleX,
  clipboardList: ClipboardList,
  clock: Clock,
  close: X,
  download: Download,
  eye: Eye,
  eyeOff: EyeOff,
  filter: Filter,
  gripVertical: GripVertical,
  home: Home,
  inboxIcon: Inbox,
  info: Info,
  layoutTemplate: LayoutTemplate,
  lifeBuoy: LifeBuoy,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  map: Map,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  minus: Minus,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  spinner: Loader2,
  sun: Sun,
  trash2: Trash2,
  triangleAlert: TriangleAlert,
  user: User,
  userCog: UserCog,
  userPlus: UserPlus,
  users: Users,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
